[package]
name = "buildkite_waiter"
version = "0.3.0"
authors = ["Liam Dawson <liam@ldaws.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["os-notifications"]
os-notifications = ["notifica"]

[dependencies]

# feature os-notifications
notifica = { version = "3.0.1", optional = true }

anyhow = "1.0.38"
chrono = { version = "0.4.19", features = ["serde"] }
chrono-humanize = "0.1.1"
clap = "2.33.3"
console = "0.14.0"
dialoguer = "0.7.1"
fern = "0.6.0"
heck = "0.3.2"
keyring = "0.10.1"
log = "0.4.13"
once_cell = "1.5.2"
secrecy = "0.7.0"
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"
structopt = "0.3.21"
thiserror = "1.0.23"
url = "2.2.0"
ureq = { version = "2.0.1", features = ["json"] }

[build-dependencies]
structopt = "0.3.21"
url = "2.2.0"
